[package]
name = "assemulator"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.26.3"
strum_macros = "0.26.3"
clap = { version = "4.5.8", features = ["derive"] }
pest = "2.7.11"
pest_derive = "2.7.11"
lazy_static = "1.5.0"
